// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN9zjkhQp1L-YM2uU_TTp-N2iXxg0kCm8',
    appId: '1:972040701571:web:08090f6a350adf2bc37db6',
    messagingSenderId: '972040701571',
    projectId: 'habit-tracker-b71b3',
    authDomain: 'habit-tracker-b71b3.firebaseapp.com',
    storageBucket: 'habit-tracker-b71b3.appspot.com',
    measurementId: 'G-99GEXJG0D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3hKPOcgvlM71-ZmcmlRynb7LuGShoWWo',
    appId: '1:972040701571:android:39e0a5e7e069c6a1c37db6',
    messagingSenderId: '972040701571',
    projectId: 'habit-tracker-b71b3',
    storageBucket: 'habit-tracker-b71b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGvyIVfyohuPhuz0Qy21IZenFsoEIqxvg',
    appId: '1:972040701571:ios:0a35a86f7dc91655c37db6',
    messagingSenderId: '972040701571',
    projectId: 'habit-tracker-b71b3',
    storageBucket: 'habit-tracker-b71b3.appspot.com',
    iosClientId: '972040701571-1rs02j7dv5bbnsvd08hoj89nb7tcfg6k.apps.googleusercontent.com',
    iosBundleId: 'com.sam.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGvyIVfyohuPhuz0Qy21IZenFsoEIqxvg',
    appId: '1:972040701571:ios:938ab6684e4cecb4c37db6',
    messagingSenderId: '972040701571',
    projectId: 'habit-tracker-b71b3',
    storageBucket: 'habit-tracker-b71b3.appspot.com',
    iosClientId: '972040701571-t404s7el84607pqvk60s0dv5clsqiden.apps.googleusercontent.com',
    iosBundleId: 'com.sam.habitTracker.RunnerTests',
  );
}
